### ISSUE TITLE
Three graph neural network papers from NIPS 2018

### ISSUE THREAD

**Issue by leuchine** [thunlp/GNNPapers#1]
Hi THUNLP:

Thanks a lot for the curated list! Here are three papers from NIPS this year, which maybe of interest to the audience. Thanks!

http://papers.nips.cc/paper/7729-hierarchical-graph-representation-learning-with-differentiable-pooling
http://papers.nips.cc/paper/8005-constrained-graph-variational-autoencoders-for-molecule-design
http://papers.nips.cc/paper/7877-graph-convolutional-policy-network-for-goal-directed-molecular-graph-generation

Best Regards,
Qi

**Comment by jayzzhou-thu** [comment]
Hi Qi, thanks for your suggestion. We have added relevant papers from NeurIPS 2018. Hope the list will help you.
