### ISSUE TITLE
Suggestion for paper: Prototype Propagation Networks (PPN) for Weakly-supervised Few-shot Learning on Category Graph

### ISSUE THREAD

**Issue by liulu112601** [thunlp/GNNPapers#10]
Hi 

Thx for keeping a good collection of GNN papers. I found it comprehensive and interesting!

Can I suggest a recent IJCAI2019 paper (also accepted for ICML workshop 2019) : Prototype Propagation Networks (PPN) for Weakly-supervised Few-shot Learning on Category Graph (https://arxiv.org/abs/1905.04042) for the addition of the list? 

This paper shows an application of GNN on few-shot learning. It would be nice to add it in.

**Comment by jayzzhou-thu** [comment]
Thanks for your suggestion and the paper has been added in the application section :)
