### ISSUE TITLE
Suggesting delete unrelated papers

### ISSUE THREAD

**Issue by zdh2292390** [thunlp/GNNPapers#12]
I found some unrelated papers in this list, such as:

Non-local Neural Networks. Wang, Xiaolong and Girshick, Ross and Gupta, Abhinav and He, Kaiming. CVPR 2018. 

Neural Message Passing for Quantum Chemistry. Gilmer, Justin and Schoenholz, Samuel S and Riley, Patrick F and Vinyals, Oriol and Dahl, George E. 2017.

**Comment by GilbertHeywood** [comment]
I think it is better to keep all for now and you can overlook some papers you believe unrelated. But papers like neural message passing are actually the important papers that re-initiated the very recent research on graph NNs.
