### ISSUE TITLE
Two missing papers

### ISSUE THREAD

**Issue by muhanzhang** [thunlp/GNNPapers#38]
Thank you for your great effort in surveying these papers. We believe you might have missed two important papers from our lab. 

M. Zhang, Z. Cui, M. Neumann, and Y. Chen, An End-to-End Deep Learning Architecture for Graph Classification, Proc. AAAI Conference on Artificial Intelligence (AAAI-18), 2018. This is the first paper to study advanced pooling layers for graph classification.

M. Zhang and Y. Chen, Link Prediction Based on Graph Neural Networks, Advances in Neural Information Processing Systems (NeurIPS-18), spotlight presentation, 2018. This is a successful GNN application in social networks and link prediction.

We would appreciate much if you can add them to the list. Thanks!

**Comment by diningphil** [comment]
Similarly to the previous comment, there are two foundational works that are missing.

Sperduti, Alessandro, and Antonina Starita. "Supervised neural networks for the classification of structures." IEEE Transactions on Neural Networks 8.3 (1997): 714-735. 
(Formalized the idea of neighbors aggregation for directed acyclic graphs)

Micheli, Alessio. "Neural network for graphs: A contextual constructive approach." IEEE Transactions on Neural Networks 20.3 (2009): 498-511.
(Work made by my supervisor. This is the very first feedforward GNN that applies spatial convolution. It was published the same year as the Graph Neural Network of Scarselli, which is not a feedforward model)

I think these would be great additions to your list of works! Thanks for your effort!

**Comment by jayzzhou-thu** [comment]
hi @muhanzhang and @diningphil , the papers are added, thanks for your suggestions!
