### ISSUE TITLE
GraphSAINT from ICLR 2020

### ISSUE THREAD

**Issue by ZimpleX** [thunlp/GNNPapers#44]
Thanks for the great collection!

I would like to point out our recent paper in ICLR 2020, "GraphSAINT: Graph sampling based inductive method". We proposed a graph sampling based minibatch training algorithm that works well on large graphs and deep GNNs. I think it fits under the "Efficiency" category of your collection. 

Our code is available via https://github.com/GraphSAINT/GraphSAINT

The PyTorch Geometric library also has a [reference implementation](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.GraphSAINTSampler).

**Comment by jayzzhou-thu** [comment]
hi @ZimpleX, we have added your interesting paper, thanks for your suggestions!
