### ISSUE TITLE
Graph Capsule CNN Related Papers

### ISSUE THREAD

**Issue by vermaMachineLearning** [thunlp/GNNPapers#6]
Great list! Feel free to add these two papers related to capsule networks. 

1) Graph Capsule Convolutional Neural Networks. Saurabh Verma, Zhi-Li Zhang (ICML workshop 2018, our paper :))
2) Capsule Graph Neural Network Zhang. Xinyi, Lihui Chen (ICLR 2019)

**Comment by jayzzhou-thu** [comment]
We've added these papers. Thanks for your suggestions!
